[project]
name = "Notas"
version = "0.1.0"
description = "Gestor de información de estudiantes desde archivos Excel"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.0",
    "openpyxl>=3.1.0",
    "requests>=2.32.3",
    "termcolor>=2.3.0"
]
